### ISSUE TITLE
NPM is not issueing the lib

### ISSUE THREAD

**Issue by jstnjns** [cif/handlebar-rider#3]
When installing using the --save flag, the lib is not actually included.  Have not tried without flag.
![Screen Shot 2013-01-07 at 3 05 45 PM](https://f.cloud.github.com/assets/249444/48751/e1d0220c-591e-11e2-9677-2762d9047028.png)

**Comment by cif** [comment]
I'm not familiar with the --save argument. Are you doing this when using handlebar-rider as dependency in a project?  

I've been installing NPM modules globally so I always have them available to future projects, then using NPM link command (https://npmjs.org/doc/link.html) to install modules into the project.
